# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('taken_by', models.ManyToManyField(related_name='prof_module_course_stud', to=settings.AUTH_USER_MODEL)),
                ('taught_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_module_course_prof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
