# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollNumberToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10)),
                ('face_token', models.CharField(max_length=50)),
            ],
        ),
    ]
