# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facesets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceset_token', models.CharField(max_length=50)),
                ('outer_id', models.CharField(max_length=50)),
            ],
        ),
    ]
