# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_module_attendance_stud', to=settings.AUTH_USER_MODEL),
        ),
    ]
