# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prof_module', '0002_auto_20170401_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('date', models.DateField(null=True)),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('0', 'IN PROGRESS'), ('1', 'ACCEPTED'), ('2', 'DECLINED')], default='0', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_module_query_stud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
