# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 10:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof_module', '0002_facesets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollnumbertoken',
            name='roll_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_module_rollnumbertoken_stud', to=settings.AUTH_USER_MODEL),
        ),
    ]
