# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=32)),
                ('account', models.CharField(choices=[('0', 'STUDENT'), ('1', 'PROFESSOR')], max_length=1)),
                ('status', models.CharField(choices=[('0', 'NOT_VERIFIED'), ('1', 'VERIFIED')], default='0', max_length=1)),
            ],
        ),
    ]
