# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='account',
            field=models.CharField(choices=[('0', 'STUDENT'), ('1', 'PROFESSOR')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
