# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_auto_20170320_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
