# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_auto_20170321_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='status',
            field=models.CharField(choices=[('0', 'NOT_VERIFIED'), ('1', 'VERIFIED')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
