# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0006_signup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.CharField(choices=[('0', 'NOT_VERIFIED'), ('1', 'VERIFIED')], default='0', max_length=1),
        ),
    ]
